#!/bin/sh

set -e

case "$1" in
    remove|purge)
        # remove GagBook config file
        rm -rf /home/user/.config/GagBook
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`\$1'" >&2
        exit 1
    ;;
esac

exit 0
