#!/bin/sh

set -e

case "$1" in
    remove|purge)
        # remove GagBook config file
        /usr/bin/aegis-exec -s -u user /bin/rm -rf /home/user/.config/GagBook || true
        # remove GagBook cache folder
        /usr/bin/aegis-exec -s -u user /bin/rm -rf /home/user/.cache/gagbook || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`\$1'" >&2
        exit 1
    ;;
esac

exit 0
